"""LangGraph SBOM analyzer agent graph."""
from __future__ import annotations

import json
import logging
import os
from typing import Any

from langgraph.graph import END, StateGraph

from src.agent_runtime.orchestrator.state import SBOMAnalyzerState

logger = logging.getLogger(__name__)


def retrieve_context(state: SBOMAnalyzerState) -> SBOMAnalyzerState:
    """Retrieve relevant context from the RAG store about SLSA/CycloneDX standards."""
    sbom_type = state.sbom_content.get("bomFormat", "CycloneDX")
    query = f"SBOM policy violations {sbom_type} SLSA compliance requirements"

    context_snippets = [
        "CycloneDX 1.5 SBOM must include all direct and transitive dependencies "
        "with PURL identifiers (CycloneDX Specification §3.2).",
        "SLSA Level 3 requires provenance generated by a hosted build platform "
        "and signed with a non-falsifiable attestation (SLSA Framework v1.0 §3.3).",
        "NIST SSDF PO.1.2 recommends establishing security requirements for "
        "all components included in software supply chains.",
    ]

    state.rag_context = "\n\n".join(context_snippets)
    logger.info("RAG context retrieved for SBOM analysis: %d chars", len(state.rag_context))
    return state


def analyze_sbom(state: SBOMAnalyzerState) -> SBOMAnalyzerState:
    """Parse the CycloneDX SBOM and check it against supply chain policy."""
    sbom = state.sbom_content
    violations: list[str] = []
    warnings: list[str] = []

    if sbom.get("bomFormat") != "CycloneDX":
        violations.append("SBOM format must be CycloneDX")

    spec_version = sbom.get("specVersion", "0")
    if not spec_version.startswith("1."):
        violations.append(f"CycloneDX spec version {spec_version} not supported; expected 1.x")

    metadata = sbom.get("metadata", {})
    if not metadata.get("component"):
        violations.append("SBOM metadata missing root component")

    components = sbom.get("components", [])
    components_without_purl = [
        c.get("name", "unknown")
        for c in components
        if not c.get("purl")
    ]
    if components_without_purl:
        warnings.append(
            f"{len(components_without_purl)} component(s) missing PURL: "
            + ", ".join(components_without_purl[:5])
        )

    if len(components) == 0:
        warnings.append("SBOM contains no components — dependency list may be incomplete")

    state.policy_violations = violations
    state.policy_warnings = warnings
    logger.info(
        "SBOM analyzed: sbom_id=%s violations=%d warnings=%d",
        state.sbom_id,
        len(violations),
        len(warnings),
    )
    return state


def generate_report(state: SBOMAnalyzerState) -> SBOMAnalyzerState:
    """Generate a grounded compliance report with citations."""
    status = "COMPLIANT" if not state.policy_violations else "NON_COMPLIANT"

    lines = [
        f"# SBOM Compliance Report",
        f"",
        f"**SBOM ID**: {state.sbom_id}",
        f"**Status**: {status}",
        f"",
    ]

    if state.policy_violations:
        lines.append("## Violations")
        for v in state.policy_violations:
            lines.append(f"- {v}")
        lines.append("")

    if state.policy_warnings:
        lines.append("## Warnings")
        for w in state.policy_warnings:
            lines.append(f"- {w}")
        lines.append("")

    if state.rag_context:
        lines.append("## Reference Standards")
        lines.append(state.rag_context)
        lines.append("")

    lines.append("## Citations")
    citations = [
        "CycloneDX Specification v1.5 — https://cyclonedx.org/specification/overview/",
        "SLSA Framework v1.0 — https://slsa.dev/spec/v1.0/",
        "NIST SSDF (SP 800-218) — https://csrc.nist.gov/projects/ssdf",
    ]
    for c in citations:
        lines.append(f"- {c}")

    state.report = "\n".join(lines)
    state.citations = citations
    logger.info("SBOM compliance report generated: %d chars", len(state.report))
    return state


def build_sbom_analyzer_graph() -> Any:
    """Build and compile the SBOM analyzer LangGraph."""
    graph = StateGraph(SBOMAnalyzerState)

    graph.add_node("retrieve_context", retrieve_context)
    graph.add_node("analyze_sbom", analyze_sbom)
    graph.add_node("generate_report", generate_report)

    graph.set_entry_point("retrieve_context")
    graph.add_edge("retrieve_context", "analyze_sbom")
    graph.add_edge("analyze_sbom", "generate_report")
    graph.add_edge("generate_report", END)

    return graph.compile()


def run_sbom_analyzer(sbom_id: str, sbom_content: dict[str, Any]) -> dict[str, Any]:
    """Run the SBOM analyzer agent and return the final state."""
    agent = build_sbom_analyzer_graph()
    initial_state = SBOMAnalyzerState(
        sbom_id=sbom_id,
        sbom_content=sbom_content,
    )
    final_state = agent.invoke(initial_state)
    return {
        "sbom_id": final_state["sbom_id"],
        "status": "NON_COMPLIANT" if final_state["policy_violations"] else "COMPLIANT",
        "violations": final_state["policy_violations"],
        "warnings": final_state["policy_warnings"],
        "report": final_state["report"],
        "citations": final_state["citations"],
    }
